services:
  base:
    build:
      context: ./bacula-base
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULA_KEY: ${BACULA_KEY}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
        BACULA_EMAIL: ${EMAIL}
    image: asrashley/bacula-base:${BACULA_VERSION}
#
  bacula-db:
    build:
      context: ./bacula-catalog
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
    image: asrashley/bacula-catalog:${BACULA_VERSION}
    restart: unless-stopped
    depends_on:
      - base
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-db
    ports:
      - 5432:5432/tcp
#
  bacula-dir:
    build:
      context: ./bacula-dir
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacula-director:${BACULA_VERSION}
    restart: unless-stopped
    environment:
      BACULA_EMAIL: ${EMAIL}
    user: ${BACULA_UID}:${BACULA_GID}
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./dir/working:/opt/bacula/working
      - ./dir/logs:/opt/bacula/log
      - ./dir/run:/run/bacula
      - ./dir/var:/var/lib/bacula
      - /Covenant/Bacula/bootstrap:/var/lib/bacula/archive
    depends_on:
      - base
      - bacula-db
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-dir
    ports:
      - 9101:9101/tcp
#
  bacula-sd:
    build:
      context: ./bacula-sd
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacularis-sd:${BACULA_VERSION}
    user: ${BACULA_UID}:${BACULA_GID}
    depends_on:
      - base
    restart: unless-stopped
    environment:
      BACULA_EMAIL: ${EMAIL}
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./sd/working:/var/lib/bacula:rw
      - /Covenant/Bacula:/store:rw
      - /restores:/restores:rw
    networks:
      - bacnet
    domainname: bacula-sd
    dns:
      - ${DNS_SERVER}
    dns_search: 
      - ${DNS_SEARCH}
    ports:
      - ${HOST_IP}:9103:9103/tcp
#
  bacula-api:
    build:
      context: ./bacula-api
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULARIS_VERSION: ${BACULARIS_VERSION}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        WWW_GID: ${WWW_GID}
        WWW_UID: ${WWW_UID}
    image: asrashley/bacularis-api-sd:${BACULA_VERSION}
    restart: unless-stopped
    environment:
      BACULA_EMAIL: ${EMAIL}
    depends_on:
      - bacula-db
      - bacula-dir
      - bacula-sd
    volumes:
      - ./etc:/etc/bacula:rw
      - ./etc:/opt/bacula/etc:rw
      - ./api/config:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config:rw
      - ./web/config:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config:rw
      - ./api/logs/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs:rw
      - ./api/logs/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs:rw
      - ./api/working:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working:rw
      - ./api/working:/var/lib/bacula:rw
    networks:
      - bacnet
    domainname: bacula-api
    dns:
      - ${DNS_SERVER}
    dns_search: 
      - ${DNS_SEARCH}
    ports:
      - 9097:9097/tcp
#
  bacula-fd:
    build:
      context: ./bacula-fd
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacula-client:${BACULA_VERSION}
    restart: unless-stopped
    environment:
      BACULA_EMAIL: ${EMAIL}
    depends_on:
      - base
      - bacula-dir
      - bacula-sd
    volumes:
      - ./etc/bacula-fd.conf:/opt/bacula/etc/bacula-fd.conf:ro
      - ./dir/working:/opt/bacula/working:rw
      - /Covenant/Bacula/bootstrap:/var/lib/bacula/archive:rw
    networks:
      - bacnet
#
  bacula-web:
    build:
      context: ./bacula-web
      args:
        BACULA_VERSION: ${BACULA_VERSION}
        BACULARIS_VERSION: ${BACULARIS_VERSION}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        WWW_GID: ${WWW_GID}
        WWW_UID: ${WWW_UID}
    image: asrashley/bacularis-web:${BACULARIS_VERSION:-5.6.0}-alpine
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - bacula-api
    volumes:
      - ./etc:/etc/bacula:rw
      - ./api/config:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config:rw
      - ./web/config:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config:rw
      - ./web/config:/var/www/bacularis/protected/Web/Config:rw
      - ./web/working:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working
      - ./web/logs/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs:rw
      - ./web/logs/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs:rw
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    ports:
      - ${HOST_IP}:9098:9097/tcp
volumes:
  pgdata:
    name: bacula15-pg10
    driver: icefo/docker-volume-zfs-plugin:2.2
    driver_opts:
        compression: zstd
        recordsize: 16k
networks:
  bacnet:
    driver: bridge
