services:
  base:
    build:
      context: ./bacula-base
      args:
        BACULA_VERSION: ${BACULA_VERSION:-15.0.2}
        BACULA_KEY: ${BACULA_KEY:-670fdff72b048}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
    image: asrashley/bacula-base:15.0.2
#
  bacula-db:
    build:
      context: ./bacula-catalog
      args:
        BACULA_VERSION: ${BACULA_VERSION:-15.0.2}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
    image: asrashley/bacula-catalog:15.0.2
    restart: unless-stopped
    depends_on:
      - base
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-db
    ports:
      - 5432:5432/tcp
#
  bacula-dir:
    build:
      context: ./bacula-dir
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacula-director:15.0.2
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./working/dir:/opt/bacula/working:rw
      - ./logs/dir:/opt/log:rw
      - /sabrent/bacula/bootstrap:/var/lib/bacula/archive:rw
    depends_on:
      - base
      - bacula-db
    networks:
      - bacnet
    links:
      - bacula-db
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-dir
    ports:
      - 9101:9101/tcp
#
  bacula-sd:
    build:
      context: ./bacula-sd
      args:
        - BACULA_GID=${BACULA_GID:-1005}
        - BACULA_UID=${BACULA_UID:-116}
    image: asrashley/bacularis-api-sd:15.0.2
    restart: unless-stopped
    volumes:
      - ./etc:/etc/bacula:rw
      - /sabrent/bacula:/store:rw
      - ./logs/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs:rw
      - ./config/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config:rw
      - ./working/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working:rw
      - ./working/sd:/var/lib/bacula:rw
      - /export/restores:/restores:rw
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    links:
      - bacula-db
    ports:
      - 9097:9097/tcp
      - 192.168.96.1:9103:9103/tcp
#
  bacula-fd:
    build:
      context: ./bacula-fd
      args:
        - BACULA_GID=${BACULA_GID:-1005}
        - BACULA_UID=${BACULA_UID:-116}
    image: asrashley/bacula-client:15.0.2
    restart: unless-stopped
    depends_on:
      - base
      - bacula-dir
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./working/dir:/opt/bacula/working:rw
      - /sabrent/bacula/bootstrap:/var/lib/bacula/archive:rw
    networks:
      - bacnet
#
  bacula-web:
    build: bacula-web
    image: asrashley/bacularis-web:5.4.0-alpine
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - bacula-sd
    volumes:
      - ./etc:/etc/bacula:ro
      - ./config/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config:rw
      - ./config/web:/var/www/bacularis/protected/Web/Config:rw
      - ./logs/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs:rw
      - ./working/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working
    networks:
      - bacnet
    links:
      - bacula-db
      - bacula-dir
      - bacula-sd
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    ports:
      - 192.168.96.1:9098:9097/tcp
volumes:
  pgdata:
    name: bacula15-pg10
    driver: icefo/docker-volume-zfs-plugin:2.2
    driver_opts:
        compression: zstd
        recordsize: 16k
networks:
  bacnet:
    driver: bridge
