services:
  base:
    build:
      context: ./bacula-base
      args:
        BACULA_VERSION: ${BACULA_VERSION:-15.0.2}
        BACULA_KEY: ${BACULA_KEY:-670fdff72b048}
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
        EMAIL: ${BACULA_EMAIL}
    image: asrashley/bacula-base:15.0.2
#
  bacula-db:
    build:
      context: ./bacula-catalog
      args:
        BACULA_VERSION: ${BACULA_VERSION:-15.0.2}
        PG_GID: ${PG_GID}
        PG_UID: ${PG_UID}
    image: asrashley/bacula-catalog:15.0.2
    restart: unless-stopped
    depends_on:
      - base
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - bacnet
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-db
    ports:
      - 5432:5432/tcp
#
  bacula-dir:
    build:
      context: ./bacula-dir
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacula-director:15.0.2
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./dir/working:/opt/bacula/working:rw
      - ./dir/logs:/opt/log:rw
      - /Covenant/Bacula/bootstrap:/var/lib/bacula/archive:rw
    depends_on:
      - base
      - bacula-db
    networks:
      - bacnet
    links:
      - bacula-db
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    domainname: bacula-dir
    ports:
      - 9101:9101/tcp
#
  bacula-sd:
    build:
      context: ./bacula-sd
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacularis-sd:15.0.2
    depends_on:
      - base
    restart: unless-stopped
    volumes:
      - ./etc/bacula-sd.conf:/opt/bacula/etc/bacula-sd.conf:ro
      - ./sd/working:/var/lib/bacula:rw
      - /Covenant/Bacula:/store:rw
      - /restores:/restores:rw
    networks:
      - bacnet
    dns: 
      - ${DNS_SERVER}
    dns_search: 
      - ${DNS_SEARCH}
    ports:
      - 192.168.96.1:9103:9103/tcp
#
  bacula-api:
    build:
      context: ./bacula-api
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        WWW_GID: ${WWW_GID}
        WWW_UID: ${WWW_UID}
    image: asrashley/bacularis-api-sd:15.0.2
    restart: unless-stopped
    depends_on:
      - bacula-db
      - bacula-dir
      - bacula-sd
    volumes:
      - ./etc:/etc/bacula:rw
      - ./etc:/opt/bacula/etc:rw
      - ./api/logs/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs:rw
      - ./api/config/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config:rw
      - ./api/empty:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs:rw
      - ./api/empty:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config:rw
      - ./api/assets:/var/www/bacularis/htdocs/assets:rw
      - ./api/runtime:/var/www/bacularis/protected/runtime:rw
      - ./api/working:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working:rw
      - ./api/working:/var/lib/bacula:rw
    networks:
      - bacnet
    dns: 
      - ${DNS_SERVER}
    dns_search: 
      - ${DNS_SEARCH}
    links:
      - bacula-db
      - bacula-sd
    ports:
      - 9097:9097/tcp
#
  bacula-fd:
    build:
      context: ./bacula-fd
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
    image: asrashley/bacula-client:15.0.2
    restart: unless-stopped
    depends_on:
      - base
      - bacula-dir
    volumes:
      - ./etc/bacula-fd.conf:/opt/bacula/etc/bacula-fd.conf:ro
      - ./dir/working:/opt/bacula/working:rw
      - /Covenant/Bacula/bootstrap:/var/lib/bacula/archive:rw
    networks:
      - bacnet
#
  bacula-web:
    build:
      context: ./bacula-web
      args:
        BACULA_GID: ${BACULA_GID}
        BACULA_UID: ${BACULA_UID}
        WWW_GID: ${WWW_GID}
        WWW_UID: ${WWW_UID}
    image: asrashley/bacularis-web:5.4.0-alpine
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - bacula-api
    volumes:
      - ./etc:/etc/bacula:rw
      - ./web/config/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config:rw
      - ./web/config/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config:rw
      - ./web/config/web:/var/www/bacularis/protected/Web/Config:rw
      - ./web/working:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working
      - ./web/assets:/var/www/bacularis/htdocs/assets:rw
      - ./web/runtime:/var/www/bacularis/protected/runtime:rw
      - ./web/logs/web:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs:rw
      - ./web/logs/api:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs:rw
    networks:
      - bacnet
    links:
      - bacula-db
      - bacula-dir
      - bacula-sd
    dns: ${DNS_SERVER}
    dns_search: ${DNS_SEARCH}
    ports:
      - 192.168.96.1:9098:9097/tcp
volumes:
  pgdata:
    name: bacula15-pg10
    driver: icefo/docker-volume-zfs-plugin:2.2
    driver_opts:
        compression: zstd
        recordsize: 16k
networks:
  bacnet:
    driver: bridge
