#!/bin/sh
#
# Copyright (C) 2000-2023 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This script deletes a catalog dump
#
db_name=bacula

rm -f /opt/bacula/working/${db_name}.sql

#
# We recommend that you email a copy of the bsr file that was
#  made for the Job that runs this script to yourself.
#  You just need to put the bsr file in /opt/bacula/working/BackupCatalog.bsr
#  or adjust the script below.	Please replace all %xxx% with what
#  is appropriate at your site.
#
#${exec_prefix}/bin/bsmtp -h %smtp-server% -s "catalog.bsr" \
#   %your-name@company.org% </opt/bacula/bsr/catalog.bsr
#
# The following script will email a summary of the backup jobs
# see baculabackupreport.ini for its settings
/opt/bacula/etc/scripts/baculabackupreport
#
